"""Agregando roles a usuarios

Revision ID: 0ad76e8e2f94
Revises: 9a83b4f119fd
Create Date: 2025-02-18 14:29:09.226399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad76e8e2f94'
down_revision = '9a83b4f119fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
