"""Corrige relación de productos con recepciones

Revision ID: 103b74d1183a
Revises: ded1a9d74769
Create Date: 2025-03-07 12:03:08.717286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '103b74d1183a'
down_revision = 'ded1a9d74769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('recepcion_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_recepcion', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recepciones', ['recepcion_id'], ['id'])

    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_partida', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cat_partida')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_recepcion', 'recepciones', ['recepcion_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('recepcion_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
