"""Nueva actualización agregado de productoBase y modificacion en producto

Revision ID: 33d0975fc673
Revises: 50fec4b02354
Create Date: 2025-02-24 16:42:56.459514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d0975fc673'
down_revision = '50fec4b02354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_base',
    sa.Column('codigo_base', sa.String(length=20), nullable=False),
    sa.Column('codigo_tango', sa.String(length=20), nullable=False),
    sa.Column('ins_mat_prod', sa.String(length=255), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('codigo_base')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_tango', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('proveedor', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('codigo_base', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'productos_base', ['codigo_base'], ['codigo_base'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('codigo_base')
        batch_op.drop_column('proveedor')
        batch_op.drop_column('codigo_tango')

    op.drop_table('productos_base')
    # ### end Alembic commands ###
