"""Nueva actualización en productos y recepciones

Revision ID: 50fec4b02354
Revises: 6d1eda6170a2
Create Date: 2025-02-21 17:06:57.679842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50fec4b02354'
down_revision = '6d1eda6170a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ins_mat_prod', sa.String(length=255), nullable=False))

    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.drop_constraint('recepciones_ibfk_1', type_='foreignkey')
        batch_op.drop_column('producto_codigo')
        batch_op.drop_column('ins_mat_prod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ins_mat_prod', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('producto_codigo', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('recepciones_ibfk_1', 'productos', ['producto_codigo'], ['codigo'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('ins_mat_prod')

    # ### end Alembic commands ###
