"""Reparación de migraciones y agregado de tabla ReferenciaPartidas

Revision ID: 6f1b27269782
Revises: a091e26106fe
Create Date: 2025-03-11 19:42:08.131906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f1b27269782'
down_revision = 'a091e26106fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partida_referencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_partida', sa.String(length=5), nullable=False),
    sa.Column('ultima_partida', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_partida')
    )
    with op.batch_alter_table('partidas_referencia', schema=None) as batch_op:
        batch_op.drop_index('cat_partida')

    op.drop_table('partidas_referencia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidas_referencia',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cat_partida', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('ultima_partida', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('partidas_referencia', schema=None) as batch_op:
        batch_op.create_index('cat_partida', ['cat_partida'], unique=True)

    op.drop_table('partida_referencia')
    # ### end Alembic commands ###
