"""Migración inicial con usuarios, productos y recepciones

Revision ID: 9a83b4f119fd
Revises: 
Create Date: 2025-02-14 18:42:12.764614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a83b4f119fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nro_lote', sa.String(length=50), nullable=False),
    sa.Column('fecha_vto', sa.Date(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('cantidad_ingresada', sa.Integer(), nullable=False),
    sa.Column('nro_partida_asignada', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('subproceso', sa.String(length=100), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=False),
    sa.Column('ins_mat_prod', sa.String(length=255), nullable=False),
    sa.Column('producto_codigo', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_codigo'], ['productos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepciones')
    op.drop_table('usuarios')
    op.drop_table('productos')
    # ### end Alembic commands ###
