"""agregado de link_FR un campo para pegar el link al formulario padre de loyal

Revision ID: 9f71117563aa
Revises: b113e2fe2775
Create Date: 2025-03-25 12:39:26.890228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f71117563aa'
down_revision = 'b113e2fe2775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_FR', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.drop_column('link_FR')

    # ### end Alembic commands ###
