"""corrige id_recepcion en productos para que pueda ser nulo al escanear

Revision ID: a091e26106fe
Revises: 103b74d1183a
Create Date: 2025-03-07 12:14:42.327540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a091e26106fe'
down_revision = '103b74d1183a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('recepcion_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('recepcion_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
