"""agregado de codigo-proveedor para id referencia en loyal en recepcion y productos

Revision ID: b113e2fe2775
Revises: e429bf6be232
Create Date: 2025-03-21 17:51:21.174477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b113e2fe2775'
down_revision = 'e429bf6be232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_proveedor', sa.String(length=20), nullable=True))

    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_proveedor', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepciones', schema=None) as batch_op:
        batch_op.drop_column('codigo_proveedor')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('codigo_proveedor')

    # ### end Alembic commands ###
