"""Agregado ID autoincremental en productos

Revision ID: d6d0db44c2af
Revises: cd15292728a9
Create Date: 2025-02-25 22:04:02.612537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d0db44c2af'
down_revision = 'cd15292728a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion_productos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'productos', ['producto_codigo'], ['codigo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion_productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
