"""Corrige relación de productos con recepciones

Revision ID: ded1a9d74769
Revises: df0430ee8825
Create Date: 2025-03-07 11:41:51.579941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ded1a9d74769'
down_revision = 'df0430ee8825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recepcion_productos')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recepcion_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'recepciones', ['recepcion_id'], ['id'])

    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_partida', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.drop_column('cat_partida')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recepcion_id')

    op.create_table('recepcion_productos',
    sa.Column('recepcion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='recepcion_productos_ibfk_3'),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], name='recepcion_productos_ibfk_2'),
    sa.PrimaryKeyConstraint('recepcion_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
