"""Corrige relación de productos con recepciones

Revision ID: df0430ee8825
Revises: d6d0db44c2af
Create Date: 2025-02-25 22:14:29.563586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df0430ee8825'
down_revision = 'd6d0db44c2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productos', ['producto_id'], ['id'])
        batch_op.drop_column('producto_codigo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion_productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_codigo', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###
