"""agregado de codigo-proveedor para id referencia en loyal

Revision ID: e429bf6be232
Revises: 6f1b27269782
Create Date: 2025-03-21 17:46:27.575511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e429bf6be232'
down_revision = '6f1b27269782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_proveedor', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos_base', schema=None) as batch_op:
        batch_op.drop_column('codigo_proveedor')

    # ### end Alembic commands ###
